language: bash
services: docker
env:
  - PHP=5.6 WP=4.9.10
  - PHP=5.6 WP=5.0.4
  - PHP=5.6 WP=5.1.1
  - PHP=5.6 WP=5.2.2
  - PHP=5.6 WP=latest
  - PHP=7.0 WP=4.9.10
  - PHP=7.0 WP=5.0.4
  - PHP=7.0 WP=5.1.1
  - PHP=7.0 WP=5.2.2
  - PHP=7.0 WP=latest
  - PHP=7.1 WP=4.9.10
  - PHP=7.1 WP=5.0.4
  - PHP=7.1 WP=5.1.1
  - PHP=7.1 WP=5.2.2
  - PHP=7.1 WP=latest
  - PHP=7.2 WP=4.9.10
  - PHP=7.2 WP=5.0.4
  - PHP=7.2 WP=5.1.1
  - PHP=7.2 WP=5.2.2
  - PHP=7.2 WP=latest
  - PHP=7.3 WP=4.9.10
  - PHP=7.3 WP=5.0.4
  - PHP=7.3 WP=5.1.1
  - PHP=7.3 WP=5.2.2
  - PHP=7.3 WP=latest
script:
  - export TAG=${DOCKER_REPO}:php-${PHP}-wp-${WP}
  - docker build . --no-cache -t "${TAG}" --build-arg PHP_VERSION="${PHP}" --build-arg WP_VERSION="${WP}"  
after_success:
  - docker login -u=$DOCKER_LOGIN -p=$DOCKER_PASSWORD
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then docker push ${DOCKER_REPO}; fi
